### PR TITLE
fixing the requirements-txt-fixer #960

### PR DESCRIPTION
**Pull request by j3962**
Hey Anthony!

I have updated the requirements_txt_fixer.py to remove duplicate entries in the requirements file as per the bug in #960 

Hope this helps!
Jay

### CODE REVIEW

**Comment by JaySharmaSdsu** [comment]
Got it! Lemme do that then!

**Comment by csibe17** [comment]
hey @JaySharmaSdsu 
what is the status of this PR?
can you please finish it?

**Comment by JaySharmaSdsu** [comment]
Hey @csibe17!
Sorry for the delay!
I will make sure to finish it off before the end of this week!

Thank you for your patience!

**Comment by asottile** [comment]
this ended up getting solved in #1014

**Pull request closed without merging**
