### PR TITLE
Report duplicate keys in check_json

### PR DESCRIPTION
**Pull request by AdityaKhursale**
Raise ValueError and return 1 if json contains duplicate keys

Fixes https://github.com/pre-commit/pre-commit-hooks/issues/554

### CODE REVIEW

**Comment by asottile** [comment]
there's a few things CI is pointing out that you'll want to fix:

from the tox output:

```
pre_commit_hooks/check_json.py      29      1      6      1    94%   15->16, 16
```

this indicates that the code on line 16 is not covered by an automated test -- there's a set of tests for this module in tests/check_json_test.py -- you can probably find some examples there to fix it

from the pre-commit output:

```
pre_commit_hooks/check_json.py:12: error: Missing type parameters for generic type "Dict"
```

this indicates that the `Dict` generic does not have its type parameters -- usually these are `Dict[str, Any]` when loading from json.  I'm also pretty sure that `Hashable` => `str` in the function signature should be changed too? not 100% sure on that though I'd have to clone and check with `pre-commit run mypy --all-files`

**Comment by AdityaKhursale** [comment]
> there's a few things CI is pointing out that you'll want to fix:
> 
> from the tox output:
> 
> ```
> pre_commit_hooks/check_json.py      29      1      6      1    94%   15->16, 16
> ```
> 
> this indicates that the code on line 16 is not covered by an automated test -- there's a set of tests for this module in tests/check_json_test.py -- you can probably find some examples there to fix it
> 
> from the pre-commit output:
> 
> ```
> pre_commit_hooks/check_json.py:12: error: Missing type parameters for generic type "Dict"
> ```
> 
> this indicates that the `Dict` generic does not have its type parameters -- usually these are `Dict[str, Any]` when loading from json. I'm also pretty sure that `Hashable` => `str` in the function signature should be changed too? not 100% sure on that though I'd have to clone and check with `pre-commit run mypy --all-files`

Thank you for the help!
Covered line no. 16 in automated tests. Will update fix for another issue.

**Comment by AdityaKhursale** [comment]
Hi @asottile 

I have fixed the things reported by CI.
Can you please review and check if PR is good to merge?

Thanks,
Aditya

**Review by asottile — APPROVED** [review]

**Pull request merged**
