### PR TITLE
check-yaml: allow duplicate keys

### PR DESCRIPTION
**Pull request by frerksaxen**
I'm currently implementing gitlab anchors in our .gitlab-ci.yml file. 
However, it requires the yaml checker to allow duplicate keys.

Therefore, I propose an optional argument to the check-yaml pre-commit that allows duplicate keys.

### CODE REVIEW

**Comment by frerksaxen** [comment]
Sorry, I did not configure the pre-commits hooks correctly before pushing. I'll fix it now.

**Comment by asottile** [comment]
there's already an option for this

**Comment by frerksaxen** [comment]
sorry, where is this option?

**Comment by asottile** [comment]
or next time [search the issue tracker](https://github.com/pre-commit/pre-commit-hooks/issues?q=is%3Aissue+duplicate+keys+is%3Aclosed) to save everyone time

**Comment by frerksaxen** [comment]
I'm sorry. I did not understand the documentation for --unsafe. May I extend the documentation for other users to not fall for the same trap and maybe safe you some time in the future?

**Pull request closed without merging**
