### PR TITLE
added dbgp (Komodo IDE debugger) package

### PR DESCRIPTION
**Pull request by agroszer**

### CODE REVIEW

**Comment by agroszer** [comment]
ohwell, https://pypi.org/project/komodo-python3-dbgp/ is just a tad better and Komodo isn't very widely used either

**Comment by asottile** [comment]
that seems dead as well -- and not popular enough to make the list?

**Comment by agroszer** [comment]
where is the bar to make the list?

**Comment by asottile** [comment]
there isn't an explicit one -- but a <5-star library that hasn't been updated in a few years doesn't seem active enough

additionally the need for such a list is diminishing due to `breakpoint`

**Pull request closed without merging**
