### PR TITLE
Use safe_load as per PyYAML documentation

### LINKED ISSUE #104: check-yaml should use `safe_load` instead of `load`

### PR DESCRIPTION
**Pull request by bdellegrazie**
resolves #104

### CODE REVIEW

**Comment by asottile** [comment]
Lg2m,  I'll verify the tests pass since Travis seems to be having issues and merge! 

Thanks!

**Comment by bdellegrazie** [comment]
Hi @asottile -  I looked at the test output, turns out safe_load doesn't use a loader so the code is even simpler now.

**Comment by asottile** [comment]
This will use the slower pure python implementation.  You can get the fast loader via `cyaml.CSafeLoader` and fall back to `yaml.SafeLoader` I believe

**Comment by bdellegrazie** [comment]
Okay, will correct.

**Comment by asottile** [comment]
You rock! Thanks for this :)

**Pull request merged**
