### PR TITLE
Add py36 to tox

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by cclauss** [comment]
continuous-integration/appveyor/pr (Windows) can not deal with Python 3.6

**Comment by asottile** [comment]
I'm confused, we're already testing against py36 in travis / appveyor:
- https://github.com/pre-commit/pre-commit-hooks/blob/5bf6c09bfa1297d3692cadd621ef95f1284e33c0/appveyor.yml#L4
- https://github.com/pre-commit/pre-commit-hooks/blob/5bf6c09bfa1297d3692cadd621ef95f1284e33c0/.travis.yml#L8

**Comment by cclauss** [comment]
You are right!  appveyor is doing the right thing.  Somehow changing tox.ini throws things out of whack.

**Comment by asottile** [comment]
I think our build is just broken currently, seems to be something that changed with some upstream dependency, I'll look into it :)

**Comment by asottile** [comment]
Seems they broke their build system: https://github.com/appveyor/ci/issues/1428

**Pull request closed without merging**
