### PR TITLE
Make it clear that this isn't a real credential

### PR DESCRIPTION
**Pull request by katzj**

### CODE REVIEW

**Comment by asottile** [comment]
this doesn't improve anything -- it's a test

**Comment by asottile** [comment]
also "dummy" is ableist language -- tend to prefer "placeholder"

**Comment by katzj** [comment]
It is a test but it avoids a scanner accidentally seeing it and deciding it's a real credential and flagging it. Happy to change it say placeholder instead though (good callout, thanks)

**Comment by asottile** [comment]
"a scanner"?

**Pull request closed without merging**
