### PR TITLE
Fix wrong target for sort-simple-yaml

### PR DESCRIPTION
**Pull request by ctcjab**
Configure sort-simple-yaml to apply to only yaml files.

### CODE REVIEW

**Comment by asottile** [comment]
if you read the docs for this hook you'll understand why the default is the way it is

**Comment by ctcjab** [comment]
Where are the docs you're referring to? I had already read the docstrings in https://github.com/pre-commit/pre-commit-hooks/blob/main/pre_commit_hooks/sort_simple_yaml.py and they all talk about YAML files, there is no mention that this hook is meant for other filetypes.

**Comment by asottile** [comment]
the README is typically the place to look first

**Comment by ctcjab** [comment]
> Note that sort-simple-yaml by default matches no files as it enforces a very specific format. You must opt in to this by setting files

I see what happened: Whoever set this hook up in the monorepo where I hit this did so via `files: ^our_team_subdirectory/` and did not include any extension matching in that regex (e.g. `[^.]+\.ya?ml$` at the end), so it ended up unintentionally rewriting .py files. Perhaps this person made the reasonable assumption that this hook was already limiting itself to yaml files.

I already fixed the regex in our repo (before even submitting this PR). I am still wondering if it makes sense to accept this PR – would including the `types: [yaml]` here not make it easier to use this hook?

**Pull request closed without merging**
