### PR TITLE
Update setup.py

### PR DESCRIPTION
**Pull request by vikalpj**
Use latest flake8 to support `# noqa: <error>`

### CODE REVIEW

**Comment by asottile** [comment]
We're neither going to pin nor pin to a beta version.  At best this will need to use `>=`

**Comment by vikalpj** [comment]
@asottile Sounds good I will update the PR when stable version is released :)

**Comment by asottile** [comment]
As a workaround you could put `additional_dependencies: ['flake8==...']` in your .pre-commit-config.yaml

**Comment by vikalpj** [comment]
aha... thanks for the tip... Let me try that 👍

**Comment by vikalpj** [comment]
@asottile closing for now will reopen when stable version is released :)

**Pull request closed without merging**
