### PR TITLE
Prepare commit message hook

### LINKED ISSUE #788: Help with prepare-commit-msg hook
Hi,

thanks for this project. May I ask you some help on some custom **prepare-commit-msg** hook I would like to implement?

Right now I did add some tests which looks promising and I even tested a simplified version of the script from local repo. Still when trying to test that from package I can not manage to make it work or test it effectively. Since I am not an expert, I did already ran out of ideas :)

The WIP is here: https://github.com/davidmpaz/pre-commit-hooks/tree/prepare-commit

The problem I would like to solve is to have more flexibility when it comes to templating the prepared message.

Thank you very much in advance for any hint or advice,
David

### PR DESCRIPTION
**Pull request by davidmpaz**
Hi,

could we consider to improve and eventually add this to mainstream please?

I did started a discussion here: #788 later on I though maybe was a better idea to make the Pull Request and work on tha basis.

The idea is to have more flexible templating for the commit message preparation. There are many organizations that use some Message formatting for linking Issues/Tickets. I pretend to improve that.

This PR adds:
* Hook definition to the pre-commit hook configuration
* Python script used as main entry point
   - Accept branches as argument to ignore formatting on those branches
   - Allow to specify patterns for branches i order to apply formatting to those branches
   - Allow for customization of the Jinja template to use
* Add tests for the previous functionality

Resolves #788,

Thanks in advance for this awesome project,

Regards,
David

### CODE REVIEW

**Comment by davidmpaz** [comment]
Hi, 

some information on why was closed would be much appreciated.

thanks,
David

**Comment by asottile** [comment]
huh weird I typed up a message and it's just gone! I'll try and remember what I said

**Comment by asottile** [comment]
appreciate the attempt but we can't just take maintenance of this.  it's not generic enough to be useful and it adds dependencies which we can't just take on. it's also named way too generically to indicate what it does

you're best to make your own repository

in the future please discuss features before spending a bunch of time on them -- nobody likes getting their hard work closed and a small bit of planning can save you that trouble

**Comment by asottile** [comment]
also can't accept non-inclusive language either

**Comment by davidmpaz** [comment]
Thank you for your comments. It was not actually too much of work, I was on the mood on it, so not big deal.

It would help me to improve myself for the future if you give me some hints were my flaws are regarding:

> it's not generic enough to be useful

and 

> also can't accept non-inclusive language either

I will follow your others suggestions as well.

**Comment by asottile** [comment]
we can really only accept things here that are "I would use this in all or most projects without modification" -- and yes there's some odds and ends but they're mostly historical artifacts from 2014 that haven't been split out yet

as for inclusive language -- "allowlist", "blocklist", and "primary" are improvements over words with racially charged origins

**Comment by davidmpaz** [comment]
Got it. Thanks! 

Even if not merged I will proceed to eliminate those non neutral texts. Was not meant to mean any of that by any reason. 

I will be using all of these in the separate repo to come, most likely.

**Pull request closed without merging**
