### PR TITLE
Properly decode file contents.

### PR DESCRIPTION
**Pull request by ohlol**
Hi, this resolves an error using the detect_aws_credentials plugin on Python 3.

### CODE REVIEW

**Comment by asottile** [comment]
`open` in python3 returns a text stream so decode isn't correct (as you can see from the test output)

Is there a specific stacktrace you're seeing?

**Comment by asottile** [comment]
my guess (without actually seeing anything) is you're hitting a case where `LANG=C` and it's using US-ASCII to read the file.

One way to force that (in a py2+py3 compatible way) would be to `import io` + `with io.open(..., encoding='UTF-8') as f:`

**Comment by ohlol** [comment]
Ya I was getting this with the plugin enabled:

```
hookid: detect-aws-credentials

Traceback (most recent call last):
  File "/Users/scott/.pre-commit/repocg6re868/py_env-default/bin/detect-aws-credentials", line 11, in <module>
    load_entry_point('pre-commit-hooks==0.6.0', 'console_scripts', 'detect-aws-credentials')()
  File "/Users/scott/.pre-commit/repocg6re868/py_env-default/lib/python3.5/site-packages/pre_commit_hooks/detect_aws_credentials.py", line 62, in main
    bad_filenames = check_file_for_aws_keys(args.filenames, keys)
  File "/Users/scott/.pre-commit/repocg6re868/py_env-default/lib/python3.5/site-packages/pre_commit_hooks/detect_aws_credentials.py", line 32, in check_file_for_aws_keys
    text_body = content.read()
  File "/Users/scott/.pre-commit/repocg6re868/py_env-default/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 5: invalid continuation byte
```

**Comment by ohlol** [comment]
Don't have LANG=C in my shell:

```% echo $LANG
en_US.UTF-8```

**Comment by asottile** [comment]
That stacktrace indicates it is attempting to read a non-UTF8 file (most likely a binary file).  The hook is somewhat-naively (until we have a better solution) set up to check every file in your repository.  Ideally it would only check text files.  There's a WIP idea / implementation of this started: https://github.com/pre-commit/pre-commit/pull/329

I think a "fix" for this would be to make this hook ignore non-text files for now, I think we've done something similar for this hook: https://github.com/pre-commit/pre-commit-hooks/commit/4a01f64c8f67ec74edd2c6c501bce8bf61ad3494 (In this case, it stops reading the files as text and instead teaches them to read them as bytes.  For binary files, this'll succeed and won't attempt to decode them to text).

Maybe an approach like that would be the one to take here?  That or you can `exclude:` files which are binary manually, but that'd be a bit unfortunate I imagine :) 

Let me know if you'd like to take a stab at this!

**Comment by asottile** [comment]
going to close this for now, it's not mergeable as-is

**Pull request closed without merging**
