### PR TITLE
feat(check-added-large-files): :sparkles: add --no-skip-lfs-files arg…

### PR DESCRIPTION
**Pull request by JulienGrv**
…ument

### CODE REVIEW

**Comment by JulienGrv** [comment]
Hi @asottile is there something missing in my pull request or is it just you don't want to add this feature?

**Comment by asottile** [comment]
it looked like spam or that you didn't mean to open a PR

**Comment by JulienGrv** [comment]
I forgot to specify a description. Would it be possible to have such a feature?

**Comment by asottile** [comment]
usually _features_ start with a discussion about the use case -- and after searching the issue tracker to find duplicates

and we don't do emoji or conventional commit garbage

**Comment by JulienGrv** [comment]
I will remove the conventional commit, I didn't mean to offend you with it.

Usually for such small change I just open a PR and discuss it in the PR but I can also start a discussion if you estimate it is necessary. The feature is to have a flag to skip the filtering of git lfs files in the check-added-large-files hook.

Should I open another PR without conventional commit or should I open a discussion first?

**Comment by asottile** [comment]
I understand _what_ but a feature needs a _why_ and tests demonstrating that _why_

**Comment by JulienGrv** [comment]
Ok, now that you point this out with the _why_, I realize that this hook is not a suitable place for this feature because it is a hook for non-lfs files and including lfs files wouldn't make sense. For LFS files, the size limit could be actually bigger. In that case what would make more sense for my use case is to have a different hook which only focuses on LFS files. I will explore this possibility and write my own hook

**Comment by asottile** [comment]
indeed -- and this is why it is always best to start with an issue for features, such that you have a discussion realizing that the problem statement you have makes no sense and that jumping to a solution is a waste of everyone's time

**Pull request closed without merging**
