### PR TITLE
first pass at #50 (yapf hook)

### PR DESCRIPTION
**Pull request by jab**

### CODE REVIEW

**Comment by guykisel** [comment]
What does the console output of this hook look like when it's fixing files? I think the autopep8 hook might be useful for comparison purposes. It runs autopep8 individually on files, and logs filenames that it's fixing.

**Comment by jab** [comment]
The console output just looks like
```
yapf wrapper..............................................................................................................................................................................Passed
```
and it would definitely be nice if it did something more like autopep8 wrapper, but see https://github.com/pre-commit/pre-commit-hooks/issues/50#issuecomment-87791248.

I actually think that the way this is currently calling yapf, the output is not even being saved.

**Comment by asottile** [comment]
So now that https://github.com/pre-commit/pre-commit/pull/287 is implemented, yapf can be used directly without needing a wrapper :D

**Comment by asottile** [comment]
well, we'll still need to mirror in some way, but at least we don't care so much about the exit code if `-i` is being used

**Comment by jab** [comment]
original PR opener here, cool to see the progress. haven't touched any of this in months - can anyone post a quick reminder what to do to try this out?

**Comment by asottile** [comment]
@jab I've set up a mirror here: https://github.com/pre-commit/mirrors-yapf

**Pull request closed without merging**
