### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by drAlberT**
Remove "forbid-submodules" hook, as it's not available in fact.

### CODE REVIEW

**Comment by drAlberT** [comment]
@asottile first of all, probably my use of "in fact" urted you, maybe I used the wrong term... I'm not mother tongue. Not my intention.

Anyway, I got an hook not found error when trying to use it, so I have looked into the hooks folder and was able to see only the "forbid-new-submodules" file...

So i guessed the was simply an old line of code in the Readme and quickly created this stupid p
PR...

Any hint about my issue then? I also cutted and pasted the hook name from the Readme to avoid my typos but no luck...

**Comment by asottile** [comment]
it's impossible to help you if you don't show your configuration or the error message you're seeing

**Comment by drAlberT** [comment]
LOL

**Comment by drAlberT** [comment]
You are so borious guy ...

For sure I'm wrong, but I was just trying to contribute (with a stupid thing btw, to an OSS project .. you continue being arrogant, no problem. I have no intention neither time to dig into your project and debug it.

One thing I can say: sounds strange that other hooks have a mention in `setup.cfg` and a dedicated file in `pre_commit_hooks` and `tests` folders and this one lacks all of these stuff ... but for sure I'm wrong.

Happy development. Cheers

**Comment by asottile** [comment]
I'm trying to help you dude but sure go off

**Pull request closed without merging**
