### PR TITLE
Add the rpdb debugger to the list of debugger packages

### PR DESCRIPTION
**Pull request by danlamanna**

### CODE REVIEW

**Comment by danlamanna** [comment]
I meant to make this a draft, WIP.

**Comment by asottile** [comment]
don't worry about broken CI, that's https://github.com/microsoft/azure-pipelines-image-generation/issues/996 :sob:

**Comment by asottile** [comment]
@danlamanna oh, is there something else you wanted to add to this? I think this is good enough to ship :+1:

**Comment by danlamanna** [comment]
Nope, all good, thanks!

**Comment by asottile** [comment]
awesome, I'll merge this once azure has reverted their release -- thanks for the patch :tada:

**Comment by asottile** [comment]
thanks for the patch!

**Pull request merged**
