### PR TITLE
Enable support for prospector

### PR DESCRIPTION
**Pull request by kouk**
https://prospector.readthedocs.org/en/master/

### CODE REVIEW

**Comment by guykisel** [comment]
With this, we could probably delete https://github.com/pre-commit/pre-commit.github.io/blob/b8a9ec65d4a5d192391c1d555634c1ad2237134e/all-repos.yaml#L17

**Comment by asottile** [comment]
Without prospector being installed I don't think this will work?  I'd rather use @guykisel's mirror either way:

```yaml
-   repo: https://github.com/guykisel/prospector-mirror
    sha: 00fbd801
    hooks:
    -   id: prospector
```

**Comment by kouk** [comment]
Hi guys, didn't know about that repo. Makes sense to keep using that I suppose.

**Comment by asottile** [comment]
Sounds great!  Here's a list of some other great hooks as well: http://pre-commit.com/hooks.html

**Pull request closed without merging**
