### PR TITLE
adds top keys list of keys in hashes to put at the top of a hash

### PR DESCRIPTION
**Pull request by dmlb2000**
This adds custom sorting to preferentially add a list of top keys
at the start of any json hash in the json document

### CODE REVIEW

**Comment by dmlb2000** [comment]
I'd like some comments on how to test this and make the diff smaller.
The `KeyToCmp` class seems a bit over complicated and suggestions
on shrinking it would be welcome.

**Comment by asottile** [comment]
So I think some of this can be simplified with functools.total_ordering, I also wonder if instead of keeping a global registry of objects whether the insertion / construction could establish the sorting.  I wouldn't worry about the performance here.

**Comment by asottile** [comment]
Oh, as for tests, I'd just put some example inputs and outputs similar to how the other examples of this hook

**Comment by dmlb2000** [comment]
@asottile 

The reason why I didn't do the sorting in the constructor was because I didn't know how simplejson would create the dictionary. If it creates an empty object then fills it with the individual key-values or if the constructor got the entirety of the key-value hash. Sorting afterwards seemed like a safer bet and tracking the objects as they get created by another code was pretty simple.

Currently, OrderedDict has an end-to-end connected linked list for keys as its data structure to handle consistent ordering. I think to make it work in `__setitem__` you'd have to copy everything out (like I'm doing in `sort()`) and put the data structures back in place sorted. The performance would suck but you wouldn't have to do tracking of all dicts at that point.

I'll definitely implement the total_ordering decorator that should reduce the need to have all the comparisons.

**Comment by asottile** [comment]
The object pairs hook is just a callback which receives a list of pairs.  You could probably implement an efficient function which returns a normal OrderedDict :)

Something like:

```python
def pairs_first(pairs, first_pairs):
    before = [pair for pair in pairs if pair[0] in first_pairs]
    after = sorted([pair for pair in pairs if pair[0] not in first_pairs])
    return collections.OrderedDict(before + after)
```

and then `functools.partial` `first_pairs` and pass that as the `object_pairs_hook`

Something like:

```python
json.loads(s, object_pairs_hook=functools.partial(pairs_first, first_pairs=...))
```

**Comment by dmlb2000** [comment]
@asottile Ah, I get it now... that's much cleaner... I'll get that fixed too.

**Comment by karcaw** [comment]
Nice!

**Comment by asottile** [comment]
Looks great!  Want to add a testing file which specifically targets your change?

**Comment by dmlb2000** [comment]
I was actually able to do some of that with the existing test files, but I can add a more comprehensive example.

**Comment by asottile** [comment]
Thanks! You rock

**Comment by dmlb2000** [comment]
Bah! Just saw something, should have changed the README.md with the new argument... Pfft.

**Comment by asottile** [comment]
Ah! Want to write up another quick PR to add some blurb to the README?

**Pull request merged**
