### PR TITLE
Only check merge conflicts on conflict commits

### PR DESCRIPTION
**Pull request by asottile**
@guykisel what do you think?

### CODE REVIEW

**Comment by guykisel** [comment]
Seems very reasonable. Did anything in particular prompt this?

**Comment by asottile** [comment]
@guykisel we check in markdown files a lot and devs would be grumpy if we suddenly started blocking those

**Comment by guykisel** [comment]
In that case, an alternative to consider (no idea if this is better or worse) is to exclude running this hook on *.md files

**Comment by guykisel** [comment]
Anyway :+1:

**Pull request merged**
