### PR TITLE
fix pre-commit-2332

### PR DESCRIPTION
**Pull request by rishabhjain1712**
Added a fix for address the issue of inconsistent mixing between tab and space indentation within the JSON content.

### CODE REVIEW

**Comment by asottile** [comment]
please in the future discuss changes before wasting time on them

**Comment by rishabhjain1712** [comment]
got it, this was my first contribution so didnt know much about how to go about these things.
will keep this in mind

**Comment by rishabhjain1712** [comment]
@asottile if you dont mind can you guide me a little on how to contribute

**Comment by asottile** [comment]
generally it's best to start with an issue describing your problem before jumping to solutioneering.  make sure it's something that's agreed upon first before spending a bunch of effort trying to build it

also unrelated to that: use a commit subject to describe _what_ your change does rather than "fix pre-commit-2332" (which I don't even know what that's a reference to? issue 2332 doesn't exist yet?)

**Pull request closed without merging**
