### PR TITLE
Make hooks.yaml a symlink of .pre-commit-hooks.yaml

### PR DESCRIPTION
**Pull request by dlgallagher**
I was getting annoyed having to `cp .pre-commit-hooks.yaml hooks.yaml` each time I added a new hook. In yelp closed-source hook repo hooks.yaml is a symlink to .pre-commit-hooks.yaml so I figured it's probably OK here. 

`ln -s .pre-commit-hooks.yaml hooks.yaml`

In this pull request the diff makes it look like the file is deleted; perhaps github doesn't have a nice way to show a type change?

### CODE REVIEW

**Comment by chriskuehl** [comment]
The reason we don't do this is because it doesn't work on windows :(

**Comment by dlgallagher** [comment]
@chriskuehl aha thanks for the sanity check on that.

**Comment by asottile** [comment]
Here's the full reasoning if curious: https://github.com/pre-commit/pre-commit/pull/470#issuecomment-274305200

**Comment by dlgallagher** [comment]
@asottile thanks for the link for background/context.

**Pull request closed without merging**
