### PR TITLE
Capitalize acronym names

### PR DESCRIPTION
**Pull request by pradyunsg**
I feel a little bad inside every time I look at these names. I finally decided to do something about it.

### CODE REVIEW

**Comment by asottile** [comment]
stylistically I actually want to go the other way and remove all the capitalization from the hook names -- would you like to do that instead? (this better matches the file extension and hook ids)

**Comment by pradyunsg** [comment]
I *strongly* prefer all-caps, since they are acronyms and should be capitalized in human-readable strings.

I think we should use all-caps for consistency with any other textual uses, instead of for-the-computer uses -- The [JSON spec](http://json.org/) uses "JSON" and the [TOML spec](https://github.com/toml-lang/toml/blob/548078574af52e79b5e172718df46de852a9bab3/README.md) uses "TOML", in their sentences. I'm pretty sure XML, YAML and others would also be doing the same.

---

I understand the consistency suggestion you make and that's definitely better than status quo. I'm happy to make that change, if you insist on not doing all caps, and I'll update the PR. Just let me know if my paragraph above persuaded you. :)

**Comment by asottile** [comment]
I'm willing to admit I'm wrong, but I'd still like them un-capitalized

while you're at it, I've been meaning to change the `name` for `name-tests-test` to `enforce test file naming` (to make it less confusing when the `--django` flag is passed) -- if you could make that fix as well as part of this that would be great :)

**Comment by pradyunsg** [comment]
I think I'm gonna drop this, since I don't really have much time anytime soon to pick this up again.

I still feel the same as I did when I opened the PR -- the acronyms should be consistently capitalized.

**Pull request closed without merging**
