### PR TITLE
Allow linking directly to each hook

### PR DESCRIPTION
**Pull request by kimsey0**
I don't know if this is something that you want to maintain, so feel free to reject the pull request. I just wanted to suggest one of the hooks from here to my team, and wished I could like directly to the correct one like https://github.com/pre-commit/pre-commit-hooks#mixed-line-ending. This pull request allows that.

### CODE REVIEW

**Comment by asottile** [comment]
I like the idea, but is there a way to do this with vanilla markdown?

**Comment by kimsey0** [comment]
Not that I can find, unfortunately. The [GitHub Flavored Markdown Spec](https://github.github.com/gfm/) doesn't seem to include any way to define named anchors, and none of [the syntaxes I've seen suggested on the web](https://johnmacfarlane.net/babelmark2/?normalize=1&text=%3Ca+name%3D%22anchorOne%22%3E%3C%2Fa%3Eone%0A%0A%5B%5D()%7B%3Aname%3D%27anchorTwo%27%7Dtwo%0A%0A%7B%3Aname%3D%27anchorThree%27%7Dthree%0A%0A%7B%23anchorFour%7Dfour) work.

**Comment by asottile** [comment]
hmmm a good compromise would be to convert them to headings I think, let's do that (and use some small heading like
```markdown
#### `hook-name`
```

**Comment by kimsey0** [comment]
I converted them to headings. It does introduce a newline after each hook name, which makes the rendered page longer, but hopefully that's OK.

I couldn't quite figure out what the max line length was supposed to be, but I removed some line breaks that seemed out of place after splitting up each hook description into a heading and a body.

**Comment by asottile** [comment]
thanks!

**Comment by kimsey0** [comment]
Thank you!

**Pull request merged**
